### ISSUE TITLE
What should our first post be?

### ISSUE THREAD

**Issue by alexgibson** [mozilla/meao#5]
First post ideas to start off in the new year:

- Generic "welcome" post (easy)
- 2017 technical road map? (this could be a good one maybe?)
- Things that broke in 2016, how we fixed them, and what we learned (I think this would be great, but maybe not for a first post).

Any other ideas / suggestions?

**Comment by alexgibson** [comment]
@mozilla/meao

**Comment by glogiotatidis** [comment]
* 2016 high level tech review and 2017 road map sounds like a great post.
* The welcome post could be a bit more interesting if we list the tools / templates / platforms used to build this blog. Super simple stack still always nice to read what ppl use imo.

**Comment by craigcook** [comment]
I think we should do all three of those suggestions. Of course only one can be "first" so really it's just a question of what order. I think a general intro is probably best for first, but we have the about page as a place for the usual "who we are and what we do" stuff so I really like the idea of the first intro post covering how this blog came about, how it's made, and what we intend to do with it. Then a 2016 retrospective, followed by the 2017 roadmap.

**Comment by jpetto** [comment]
I like a 2016 retrospective + 2017 roadmap as a first post, maybe starting out with a link to the about page to call it out.

Also really like the idea of follow-up posts talking about the different tech we use and why.

**Comment by jgmize** [comment]
First post is live: https://mozilla.github.io/meao/
