### ISSUE TITLE
Atom / RSS feed is broken

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/meao#9]
There's a link to https://mozilla.github.io/atom.xml in our index.html but it's a 404

**Comment by alexgibson** [comment]
This is the real URL, bud oddly it's not showing the first post we published https://mozilla.github.io/meao/atom.xml

**Comment by alexgibson** [comment]
Fixed in 98066817a863d925c623ccd663e4b42e4cb34f9d - thanks @glogiotatidis 👍

**Comment by glogiotatidis** [comment]
Thank you @alexgibson  :)
